version: '3.8'
services:
  rasa-server:
    image: rasa/rasa:2.8.2-full
    container_name: rasa_server
    volumes: 
      - .:/app
    ports:
      - 5005:5005
    command: run -m models --enable-api --cors "*"
  action-server:
    image: rasa/rasa-sdk
    container_name: action_server
    volumes:
     - ./actions:/app/actions
    ports:
      - 5055:5055
    depends_on:
      - rasa-server
